# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10
cache: cocoapods
podfile: Example/Podfile
rvm:
- 2.4.1
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod update --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/RBSRealmBrowser.xcworkspace -scheme RBSRealmBrowser CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- pod lib lint --quick
